### ISSUE TITLE
Android support for xbee sx development kit (FT4232H)

### ISSUE THREAD

**Issue by marlon1300** [digidotcom/XBeeJavaLibrary#101]
Is xbee sx with the FT4232H Quad HS USB-UART/FIFO IC supported in the latest release? 

XbeeManager sample seems not recognizing sx module. Which firmware should be used?

**Comment by rubenmoral** [comment]
Hi @marlon1300,

Thanks for reporting this issue, there was an error when initializing the SX module. It's now fixed in `master`.

If you want to use the fix in your `XBeeManager` sample, you can compile and package the library (`mvn clean package`) and then replace the `xbee-java-library-1.2.0.jar` file of the example with the generated artifact.

Regards.
