### ISSUE TITLE
ReceiveData example doesn't wait for input.

### ISSUE THREAD

**Issue by murraytodd** [digidotcom/XBeeJavaLibrary#35]
The com.digi.xbee.api.receivedata.MainApp class does provide a visual description of how to register a listener, but I think there's a problem with the example because immediately after registering the listener, the application's main() function simply exits.

I'm writing this as an issue because it's not going to work (and might confused reader) but more importantly I was trying to understand how someone would most appropriately wait for input—i.e. to write a basic server application.

I've been digging through the source code, and I now understand that calling the XBeeDevice's open() method will create the DataReader Thread and call start() on it. That is, I get that this library creates its own thread for handling the packet delivery events, but what should I do with the main thread? Should I just put something like Thread.sleep(10000) in a loop, or should I be calling wait() on the XBeeDevice's getConnectionInterface() object?

Going a little deeper into this, if I were wanting to write something that used the Java EE standards, I'm not supposed to be creating my own threads, but rather using managed threads i.e. implementing Runnable or Callable, right?

Any guidelines on how a person should be creating a basic server-style app for the Coordinator would be appreciated. I.e. if looping on Thread.sleep(someBigNumber) is sufficient and appropriate, that would be great. I just suggest it gets put into the ReceiveData example.

**Comment by daescalona** [comment]
Hello Murray,

You are true, the main thread exits just after registering the listener, but application is still alive because the DataReader thread is running. From a graphic user interface application this should not supose any problem, but from a command line application this may result a bit tricky. The Thread.sleep approach should be enough, but maybe we should update the sample to wait for a carriage return after registering the listener and leave main thread waiting for that input. Once the carriage return is received the main thread removes the listener, closes the XBee connection and exists.

It has not been done that way because we wanted to maintain the code simple and clear, with theminimum required library calls.
